# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemindVoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remind_text', models.TextField()),
                ('remind_voice_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
