# Generated by Django 5.2.4 on 2025-08-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("mock", "Mock"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        default="mock",
                        max_length=16,
                    ),
                ),
                ("send_at", models.DateTimeField(db_index=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retries", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("schedule_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-send_at"],
            },
        ),
        migrations.DeleteModel(
            name="RemindVoice",
        ),
    ]
