# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecallAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_url', models.URLField()),
                ('transcript', models.TextField()),
                ('response_time', models.FloatField()),
                ('word_count', models.IntegerField()),
                ('repetition_count', models.IntegerField()),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('audio_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('avg_word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
