# Generated by Django 5.2.4 on 2025-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="voice_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
