# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingVoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('briefing_text', models.TextField()),
                ('briefing_voice_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_url', models.URLField()),
                ('transcript', models.TextField()),
                ('parsed_title', models.CharField(max_length=255)),
                ('parsed_date', models.DateField()),
                ('parsed_time', models.TimeField()),
                ('parsed_ampm', models.CharField(choices=[('AM', '오전'), ('PM', '오후')], max_length=2)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('registered_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
            ],
        ),
    ]
