# Generated by Django 5.2.4 on 2025-08-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleStep",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("step_number", models.IntegerField()),
                ("voice_url", models.URLField()),
                ("transcript", models.TextField()),
                (
                    "parsed_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="schedule.schedule",
                    ),
                ),
            ],
        ),
    ]
