# Generated by Django 5.2.4 on 2025-08-28 02:18

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
